# This workflow builds the SDK using Java 11
name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published]
jobs:
  # Build and test the SDK
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # All history
    - name: Set SDK version
      run: |
        SDK_VERSION=$(git describe --tags || echo v0.0.0-$(git rev-list --all --count)-g$(git rev-parse --short HEAD))
        SDK_VERSION="${SDK_VERSION:1}"
        echo "SDK_VERSION=${SDK_VERSION}"
        echo "TP_SDK_VERSION=${SDK_VERSION}" >> $GITHUB_ENV
    - name: Mark build as release
      if: startsWith(github.ref, 'refs/tags/v')
      run: echo "SDK_BUILD_ARGS=-Prelease=true" >> $GITHUB_ENV
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -x test -Pversion=$TP_SDK_VERSION $SDK_BUILD_ARGS
    - name: Define FULL jar name
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        if [ -z "$SDK_BUILD_ARGS" ]
        then
          export TP_SDK_VARIANT="SNAPSHOT"
          echo $TP_SDK_VARIANT >> $GITHUB_ENV
        else
          export TP_SDK_VARIANT="RELEASE"
        fi
        echo $TP_SDK_VARIANT >> $GITHUB_ENV
        export TP_SDK_JAR_NAME="testproject-java-sdk"
        echo $TP_SDK_JAR_NAME >> $GITHUB_ENV  
        export TP_SDK_FULL_JAR_EXT="FULL.jar"
        echo $TP_SDK_FULL_JAR_EXT >> $GITHUB_ENV
        echo "TP_SDK_JAR_EXT=.jar" >> $GITHUB_ENV
    - name: Upload FULL jar to release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/libs/${{ env.TP_SDK_JAR_NAME }}-${{ env.TP_SDK_VERSION }}-${{ env.TP_SDK_VARIANT}}-${{ env.TP_SDK_FULL_JAR_EXT }}
        asset_name: ${{ env.TP_SDK_JAR_NAME }}${{ env.TP_SDK_JAR_EXT }}
        tag: ${{ github.ref }}
        overwrite: true
    - name: Create jar's hash file 
      run: |
        md5=($(md5sum build/libs/${{ env.TP_SDK_JAR_NAME }}-${{ env.TP_SDK_VERSION }}-${{ env.TP_SDK_VARIANT}}-${{ env.TP_SDK_FULL_JAR_EXT }}))
        echo md5 >>  build/libs/jar-hash.txt
    - name: Upload hash artifact
      uses: actions/upload-artifact@v2
      with:
        name: Asset Hashes
        path: build/libs/jar-hash.txt
