# This workflow builds the SDK using Java 11
name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published]
jobs:
  # Build and test the SDK
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # All history
    - name: Set SDK version
      run: |
        SDK_VERSION=$(git describe --tags || echo v0.0.0-$(git rev-list --all --count)-g$(git rev-parse --short HEAD))
        SDK_VERSION="${SDK_VERSION:1}"
        echo "SDK_VERSION=${SDK_VERSION}"
        echo "TP_SDK_VERSION=${SDK_VERSION}" >> $GITHUB_ENV
    - name: Mark build as release
      if: startsWith(github.ref, 'refs/tags/v')
      run: echo "SDK_BUILD_ARGS=-Prelease=true" >> $GITHUB_ENV
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -x test -Pversion=$TP_SDK_VERSION $SDK_BUILD_ARGS
    - name: Print build file names
      run: |
        ls build/libs
        export FULL_JAR_PATH="$(find build/libs -name '*-FULL.jar')"
        echo $FULL_JAR_PATH
        echo $"SDK_BUILD_ARGS"
    - name: Upload FULL jar to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/libs/testproject-java-sdk-${{ env.TP_SDK_VERSION }}-${{ env.SNAP_REL}}-FULL.jar
        asset_name: target/release/jarFile.jar
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"
