# This workflow builds the SDK using Java 11
name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published]
jobs:
  # Build and test the SDK
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # All history
    - name: Set SDK version
      run: |
        SDK_VERSION=$(git describe --tags || echo v0.0.0-$(git rev-list --all --count)-g$(git rev-parse --short HEAD))
        SDK_VERSION="${SDK_VERSION:1}"
        echo "SDK_VERSION=${SDK_VERSION}"
        echo "TP_SDK_VERSION=${SDK_VERSION}" >> $GITHUB_ENV
    - name: Mark build as release
      if: startsWith(github.ref, 'refs/tags/v')
      run: echo "SDK_BUILD_ARGS=-Prelease=true" >> $GITHUB_ENV
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -x test -Pversion=$TP_SDK_VERSION $SDK_BUILD_ARGS
    - name: Run TestProject Agent
      env:
        TP_API_KEY: "RolV94Hs7wH11cpMHO0bREz2T_07rcT5QRRnxI9ak7w1"
      run: |
        envsubst < .github/ci/docker-compose.yml > docker-compose.yml
        docker-compose -f docker-compose.yml up -d
    - name: Wait for Agent to Register
      run: |
        trap 'kill $(jobs -p)' EXIT

        attempt_counter=0
        max_attempts=45

        mkdir -p build/reports/agent
        docker-compose -f docker-compose.yml logs -f | tee build/reports/agent/log.txt&
        until curl -s http://localhost:8585/api/status | jq '.registered' | grep true; do
          if [ ${attempt_counter} -eq ${max_attempts} ]; then
            echo "Agent failed to register. Terminating..."
            exit 1
          fi
          attempt_counter=$(($attempt_counter+1))
          sleep 1
        done
    - name: Run tests
      env:
        TP_DEV_TOKEN: "XJP7-R84sjfF0LaZjDfezQjqqxIj2ErUljqlyzKXUlo1"
        TP_AGENT_URL: http://localhost:8585
      run: |
        trap 'kill $(jobs -p)' EXIT
        export TP_DEBUG_SDK_VERSION=$TP_SDK_VERSION
        docker-compose -f docker-compose.yml logs -f --tail=0 >> build/reports/agent/log.txt&
        ./gradlew test --tests io.testproject.sdk.tests.ci.* -Pversion=$TP_SDK_VERSION $SDK_BUILD_ARGS
    - name: Archive reports
      if: ${{ failure() }}
      uses: actions/upload-artifact@v1
      with:
        name: reports
        path: build/reports
