# This workflow builds the SDK using Java 11
name: Build

on:
  workflow_call:
  
jobs:
  # Build and test the SDK
  reusable_build_and_test_workflow_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # All history
    - name: Set SDK version
      run: |
        SDK_VERSION=$(git describe --tags || echo v0.0.0-$(git rev-list --all --count)-g$(git rev-parse --short HEAD))
        SDK_VERSION="${SDK_VERSION:1}"
        echo "SDK_VERSION=${SDK_VERSION}"
        echo "TP_SDK_VERSION=${SDK_VERSION}" >> $GITHUB_ENV
    - name: Mark build as release
      if: startsWith(github.ref, 'refs/tags/v')
      run: echo "SDK_BUILD_ARGS=-Prelease=true" >> $GITHUB_ENV
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -x test -Pversion=$TP_SDK_VERSION $SDK_BUILD_ARGS
    - name: Define uberJAR file name
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        export TP_SDK_JAR_NAME="testproject-java-sdk.jar"
        echo "TP_SDK_JAR_NAME=testproject-java-sdk.jar" >> $GITHUB_ENV
        cp build/libs/*UBER.jar build/libs/"${TP_SDK_JAR_NAME}"
    - name: Upload uberJAR workflow artifact
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-artifact@v2
      with:
        name: uberJAR.jar
        path: build/libs/{{ env.TP_SDK_JAR_NAME }}
