# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  release:
    types: [created]

jobs:

  build_and_test:
    uses: ./.github/workflows/build.yml
  job2:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        name: uberJAR.jar
    - name: Upload uberJAR to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: '**/*uberJAR.jar'
        asset_name: ${{ env.TP_SDK_JAR_NAME }}${{ env.TP_SDK_JAR_EXT }}
        tag: ${{ github.ref }}
        overwrite: true
    - name: Create uberJAR hash file
      run: |
        md5sum **/*uberJAR.jar > jar-hash.md
    - name: Upload hash artifact
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: '**/*jar-hash.md'
        asset_name: ${{ env.TP_SDK_JAR_NAME }}.md5
        tag: ${{ github.ref }}
        overwrite: true
